### ISSUE TITLE
PULL_REQUEST_TEMPLATE

### ISSUE THREAD

**Issue by Vyvy-vi** [ScalantCommunity/.github#3]
We need to add a `PULL_REQUEST_TEMPLATE.md` to this repository. This PR template would be used as a default by the whole organisation by default, whenever someone is opening a PR.

refer - https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by Vyvy-vi** [comment]
closed by #7 ([71e82ce](https://github.com/ScalantCommunity/.github/commit/71e82ce7969b5d5b2118c116e84a096405c758d9))

**Comment by Spyder15** [comment]
Done
