### ISSUE TITLE
CODE_OF_CONDUCT

### ISSUE THREAD

**Issue by Vyvy-vi** [ScalantCommunity/.github#4]
Set up a `CODE_OF_CONDUCT.md` file that highlights the code of conduct of our community.
You could use the Contributor Covenant (https://www.contributor-covenant.org/version/2/1/code_of_conduct/code_of_conduct.md) or Citizen's Code of Conduct (https://web.archive.org/web/20200330154000/http://citizencodeofconduct.org/).

**Comment by Spyder15** [comment]
Done
