### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by Vyvy-vi** [ScalantCommunity/.github#5]
### Description
Add a `CONTRIBUTING.md` file in this repo that outlines the contribution process and guides contributors about:
- opening an issue and being assigned to that issue before working on anything
- forking before making cloning locally
- setting up upstream in local repository and keeping their forks up to date
- creating a new branch and pushing that branch to github instead of using `main` or `master` (default branch)
- writing conventional commits
- opening a PR

### Aditional Information
Refer https://github.com/Vyvy-vi/TearDrops/blob/main/CONTRIBUTING.md

**Comment by Spyder15** [comment]
Done
